### PR TITLE
Split out streams for 'lifetime' time periods

### LINKED ISSUE #14: user_insights_daily only capturing the last day when using target-sqlite
I am trying to get the history of insights by day over time. With the user_insights_* feeds, I am only seeing the latest days data persisted to sqlite, despite setting the appropriate date boundaries in the config.

I can see the relevant queries in the Graph API query history and meltano is paginating through previous dates, but only the latest gets inserted into the table.

Is it somehow related to the `primary_keys = ["id"]` set on these streams? Does the PK need to be [id, end_time] to retain all the rows? When I run the extractor using `target-jsonl` I can see all the previous days in the output file which makes me think it is PK/upsert related.

https://github.com/voxmedia/tap-instagram/blob/a617855de95ea03c727c0a34551097187153a943/tap_instagram/streams.py#L725

EDIT: Just starting to realise I think this this is related to #13 :)

### PR DESCRIPTION
**Pull request by acarter24**
Fixing issue with certain streams failing looking for an `end_time` when it was not present.

Also adds `end_time` to the PK list for Period stream to allow for collection of historical periods, otherwise the replication is on id only and overwrites last periods values.

Resolves #14 #13

### CODE REVIEW

**Comment by prratek** [comment]
Thanks @acarter24! This approach broadly makes sense to me and we can get around to reviewing and merging in the next couple of weeks. If you have steps to reproduce the SQLite error in particular that would make it easier for us to test that it resolves that issue (and doesn't break our usage with `target-bigquery` in any way)

**Comment by acarter24** [comment]
Cheers. In terms of reproducing the error, I pretty much just downloaded the tap and ran it and got the error.

meltano, version 2.16.1
python 3.10

Would the json payload from the API be useful?

**Comment by prratek** [comment]
Nope, shouldn't need the payload! Other info that would be helpful:
* What target (and variant) did you use?
* Any stream selection rules

**Comment by acarter24** [comment]
To recreate:

Loaders: https://github.com/MeltanoLabs/target-sqlite and https://github.com/jwills/target-duckdb both show the issue

Stream selection to narrow it down to failing stream only
```
    select:
    - user_insights_audience.*
```

NB if I invert the filter, clear state etc, it completes without issue :

```
    select:
    - !user_insights_audience.*
    - *.*
```

EDIT:Just FYI I was also able to solve one part of the issue by overriding key-properties in `meltano.yml` for the relevant tables

```
  - name: tap-instagram
    variant: voxmedia
    pip_url: tap-instagram
    config:
      ig_user_ids: ${TAP_INSTAGRAM_IG_USER_IDS}
      access_token: ${TAP_INSTAGRAM_ACCESS_TOKEN}
      start_date: 2023-03-01
    metadata:
      user_insights_*:
        key-properties: ["end_time", "id"]
    select:
    - '*.*'
    - '!user_insights_audience.*'
```

**Pull request closed without merging**
